apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: openmeteo-data
  namespace: bigdata
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000 # time that events are stored by brokers; after this duration, clear
    segment.bytes: 52428800 # segmentation size of topic data; here, 1GB