apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-producer
  namespace: bigdata
  labels:
    app: stream-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-producer
  template:
    metadata:
      labels:
        app: stream-producer
    spec:
      containers:
        - name: stream-producer
          image: mquan1503/bigdata-simulator:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-u", "/app/stream_producer.py"]
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: STREAMING_KAFKA_TOPIC
              value: stream-topic
            - name: STREAM_SEND_INTERVAL_MS
              value: "50"
            - name: STREAM_LOOP_FILES
              value: "false"
            - name: PRODUCER_IDLE_AFTER_COMPLETE
              value: "true"
            - name: PRODUCER_IDLE_SLEEP_SEC
              value: "3600"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
