apiVersion: batch/v1
kind: Job
metadata:
  name: stream-producer
  namespace: bigdata
  labels:
    app: stream-producer
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: stream-producer
    spec:
      restartPolicy: Never
      containers:
        - name: stream-producer
          image: mquan1503/bigdata-simulator:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-u", "/app/stream_producer.py"]
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: STREAMING_KAFKA_TOPIC
              value: stream-topic
            - name: STREAM_SEND_INTERVAL_MS
              value: "50"
            - name: STREAM_LOOP_FILES
              value: "false"
            - name: PRODUCER_IDLE_AFTER_COMPLETE
              value: "false"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
