import os

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_TOPIC = os.getenv("BATCH_KAFKA_TOPIC")
KAFKA_GROUP_ID = os.getenv("BATCH_KAFKA_GROUP_ID")
KAFKA_CONSUMER_POLL_TIMEOUT = os.getenv("KAFKA_CONSUMER_POLL_TIMEOUT")
FLUSH_SIZE = int(os.getenv("BATCH_FLUSH_SIZE"))

HDFS_URL = os.getenv("HDFS_URL")
HDFS_BASE_PATH = os.getenv("HDFS_BASE_PATH")
HDFS_USER = os.getenv("HDFS_USER")
HDFS_RETRY_COUNT = int(os.getenv("HDFS_RETRY_COUNT"))
HDFS_RETRY_DELAY = int(os.getenv("HDFS_RETRY_DELAY"))