FROM python:3.12-slim

WORKDIR /app

COPY core/services/simulator/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY core/services/simulator .

CMD ["python", "stream_simulator.py"]