FROM python:3.12-slim

WORKDIR /app

COPY core/services/dashboard/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY core/services/dashboard /app

CMD ["python", "app.py"]