FROM python:3.12-slim

WORKDIR /app

COPY core/simulator/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY core/simulator /app
COPY data/batch /data/csv
COPY data/streaming /data/streaming
