apiVersion: batch/v1
kind: Job
metadata:
  name: batch-trainer
  namespace: bigdata
  labels:
    app: batch-trainer
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: batch-trainer
    spec:
      restartPolicy: Never

      containers:
        - name: batch-trainer
          image: mquan1503/bigdata-batch:latest
          command: ["python3", "/app/trainer.py"]

          envFrom:
            - configMapRef:
                name: config
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          resources:
            requests:
              memory: "4Gi"
              cpu: "0.2"
            limits:
              memory: "6Gi"
              cpu: "3"
