apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: bigdata
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow-sa
      securityContext:
        fsGroup: 0
      containers:
        - name: scheduler
          image: mquan1503/bigdata-airflow:latest
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c", "airflow scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secrets
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
          resources:
            requests:
              cpu: "50m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: bigdata
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      serviceAccountName: airflow-sa
      securityContext:
        fsGroup: 0
      containers:
        - name: webserver
          image: mquan1503/bigdata-airflow:latest
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c", "airflow webserver"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secrets
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 12
          resources:
            requests:
              cpu: "50m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
