apiVersion: batch/v1
kind: Job
metadata:
  name: batch-producer
  namespace: bigdata
  labels:
    app: batch-producer
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: batch-producer
    spec:
      restartPolicy: Never
      containers:
        - name: batch-producer
          image: mquan1503/bigdata-simulator:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "-u", "/app/batch_producer.py"]
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: BATCH_LOOP_FILES
              value: "false"
            - name: PRODUCER_IDLE_AFTER_COMPLETE
              value: "false"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
